/*
 * This file is generated by jOOQ.
 */
package com.revolut.demo.jooq.model.revolut_db_4;


import com.revolut.demo.jooq.model.DefaultCatalog;
import com.revolut.demo.jooq.model.revolut_db_4.tables.Account;
import com.revolut.demo.jooq.model.revolut_db_4.tables.AccountTransactions;
import com.revolut.demo.jooq.model.revolut_db_4.tables.User;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.processing.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class RevolutDb_4 extends SchemaImpl {

    private static final long serialVersionUID = -1851462520;

    /**
     * The reference instance of <code>REVOLUT_DB_4</code>
     */
    public static final RevolutDb_4 REVOLUT_DB_4 = new RevolutDb_4();

    /**
     * The table <code>REVOLUT_DB_4.ACCOUNT</code>.
     */
    public final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>REVOLUT_DB_4.ACCOUNT_TRANSACTIONS</code>.
     */
    public final AccountTransactions ACCOUNT_TRANSACTIONS = AccountTransactions.ACCOUNT_TRANSACTIONS;

    /**
     * The table <code>REVOLUT_DB_4.USER</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private RevolutDb_4() {
        super("REVOLUT_DB_4", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
                Account.ACCOUNT,
                AccountTransactions.ACCOUNT_TRANSACTIONS,
                User.USER);
    }
}
