/*
 * This file is generated by jOOQ.
 */
package com.revolut.demo.jooq.model;


import com.revolut.demo.jooq.model.revolut_db_4.RevolutDb_4;
import org.jooq.Schema;
import org.jooq.impl.CatalogImpl;

import javax.annotation.processing.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class DefaultCatalog extends CatalogImpl {

    private static final long serialVersionUID = -1148202601;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultCatalog DEFAULT_CATALOG = new DefaultCatalog();

    /**
     * The schema <code>REVOLUT_DB_4</code>.
     */
    public final RevolutDb_4 REVOLUT_DB_4 = RevolutDb_4.REVOLUT_DB_4;

    /**
     * No further instances allowed
     */
    private DefaultCatalog() {
        super("");
    }

    @Override
    public final List<Schema> getSchemas() {
        List result = new ArrayList();
        result.addAll(getSchemas0());
        return result;
    }

    private final List<Schema> getSchemas0() {
        return Arrays.<Schema>asList(
                RevolutDb_4.REVOLUT_DB_4);
    }
}
