/*
 * This file is generated by jOOQ.
 */
package com.revolut.demo.jooq.model.revolut_schema;


import com.revolut.demo.jooq.model.revolut_schema.tables.Account;
import com.revolut.demo.jooq.model.revolut_schema.tables.AccountTransactions;
import com.revolut.demo.jooq.model.revolut_schema.tables.User;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in REVOLUT_SCHEMA
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>REVOLUT_SCHEMA.ACCOUNT</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>REVOLUT_SCHEMA.ACCOUNT_TRANSACTIONS</code>.
     */
    public static final AccountTransactions ACCOUNT_TRANSACTIONS = AccountTransactions.ACCOUNT_TRANSACTIONS;

    /**
     * The table <code>REVOLUT_SCHEMA.USER</code>.
     */
    public static final User USER = User.USER;
}
